// QR lead-tracking redirect: /q/<code> → logs a 'scan' event, resolves the
// code to its contractor + physical-marketing label, and forwards to
// intake.html tagged with that source. This is the first of the three
// funnel events (scan → form_opened → submitted, see the migration/PR
// description); logging happens here, BEFORE the form ever renders, so a
// scan that never converts into a submitted lead is still real, visible
// data, not silently lost.
//
// Modeled on functions/img/[[path]].js: narrow path validation, then either
// serve a fallback or forward upstream. Fire-and-forget logging (waitUntil)
// so a slow/failed log write never delays the redirect the scanner is
// waiting on.

const SUPABASE = 'https://mwtsmctajhrrybblgorf.supabase.co';
// Anon key — same publicly-embeddable key already inline in intake.html.
// Anon keys are protected by RLS, not secrecy, this is the intended pattern.
const SUPA_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dHNtY3RhamhycnliYmxnb3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNjIwNjMsImV4cCI6MjA5MDczODA2M30.-FMn1pEs9PpCvv8eGwSbtucWAWvcfEcQ1SYx4nD207M';

export async function onRequest(context) {
  const { request, waitUntil } = context;
  if (request.method !== 'GET' && request.method !== 'HEAD') {
    return new Response('Method not allowed', { status: 405 });
  }

  const url = new URL(request.url);
  const code = url.pathname.replace(/^\/q\//, '');
  // Codes are generated by _qrGenCode() (js/qr-leads.js): lowercase base36,
  // fixed length. Reject anything else outright rather than passing an
  // attacker-controlled string into a query filter.
  if (!/^[a-z0-9]{6,16}$/.test(code)) {
    return Response.redirect(url.origin + '/intake.html', 302);
  }

  const lookupRes = await fetch(
    SUPABASE + '/rest/v1/qr_sources?code=eq.' + encodeURIComponent(code) + '&select=account_id',
    { headers: { apikey: SUPA_ANON_KEY, Authorization: 'Bearer ' + SUPA_ANON_KEY } }
  ).catch(() => null);
  const rows = lookupRes && lookupRes.ok ? await lookupRes.json().catch(() => []) : [];
  const accountId = rows && rows[0] && rows[0].account_id;

  // Fire-and-forget: log the scan even if it turns out to be an unmatched
  // code (log-qr-event no-ops gracefully on an unknown code, see its own
  // comment) — never block or fail the redirect on this.
  const logScan = fetch(SUPABASE + '/functions/v1/log-qr-event', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + SUPA_ANON_KEY },
    body: JSON.stringify({ code, event: 'scan' }),
  }).catch(() => {});
  if (typeof waitUntil === 'function') waitUntil(logScan);

  if (!accountId) {
    // Unmatched code (typo, damaged print, deleted source) — intake.html's
    // own "no account" state already reads correctly here: the scanner did
    // scan a real code, it just isn't one we recognize.
    return Response.redirect(url.origin + '/intake.html', 302);
  }

  return Response.redirect(
    url.origin + '/intake.html?a=' + encodeURIComponent(accountId) + '&src=' + encodeURIComponent(code),
    302
  );
}
