#!/usr/bin/env python3
"""Regenerate scripts/ci/geo-fences-equivalence.sql from the shared fixture.

ONE fixture, TWO implementations. tests/e2e-geo-fences-server.spec.js runs
_geoDeriveFences (the browser half) against tests/fixtures/geo-fences-case.json;
the SQL this writes runs geo_fences_for (the server half) against the same file.
The fence list is the only piece of the deriver that exists twice, so it is the
only piece that can drift, and this is what stops it.

Run after editing the fixture. Never hand-edit the generated SQL.
"""
import json, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
case = json.loads((root / 'tests/fixtures/geo-fences-case.json').read_text())
uid = '00000000-0000-4000-8000-0000000000fe'
q = lambda o: json.dumps(o).replace("'", "''")

seed = [f"insert into zj_data(user_id, settings) values ('{uid}', '{q(case['settings'])}');"]
for t, key in (('td_places', 'places'), ('td_clients', 'clients'), ('td_jobs', 'jobs')):
    for r in case[key]:
        seed.append(f"insert into {t}(id,user_id,data) values ('{r['id']}','{uid}','{q(r)}');")

exp = ",\n    ".join(
    "('{id}','{kind}','{name}',{lat}::double precision,{lng}::double precision,{sch},{per})".format(
        id=f['id'], kind=f['kind'], name=f['name'].replace("'", "''"),
        lat=f['lat'], lng=f['lng'],
        sch='null::boolean' if f['scheduled'] is None else str(f['scheduled']).lower(),
        per='null::boolean' if f.get('personal') is None else str(f['personal']).lower())
    for f in sorted(case['expect'], key=lambda f: f['id']))

out = f"""\\set ON_ERROR_STOP on
-- GENERATED by scripts/ci/gen-geo-fences-equivalence.py from
-- tests/fixtures/geo-fences-case.json. Do not hand-edit.
--
-- The SQL half of the fence equivalence. The browser half is
-- tests/e2e-geo-fences-server.spec.js, running _geoDeriveFences against the
-- SAME fixture. geoDeriveDay is pure and portable; the fence list is not, so
-- it has to exist twice, and this is what keeps the two from drifting.

begin;
-- The fixture user must exist: zj_data and every td_* table key to auth.users.
insert into auth.users(id, email) values ('{uid}','fixture@geo-fences.test')
  on conflict (id) do nothing;
create temp table _fx_expect(id text, kind text, name text, lat double precision,
                             lng double precision, scheduled boolean,
                             personal boolean) on commit drop;
insert into _fx_expect values
    {exp};

{chr(10).join(seed)}

do $chk$
declare missing text; extra text; n int;
begin
  select string_agg(id, ', ' order by id) into missing from (
    select e.id from _fx_expect e
    left join geo_fences_for('{uid}','{case['day']}') g
      on g.id = e.id and g.kind = e.kind and g.name = e.name
     and round(g.lat::numeric,6) = round(e.lat::numeric,6)
     and round(g.lng::numeric,6) = round(e.lng::numeric,6)
     and g.scheduled is not distinct from e.scheduled
     and g.personal is not distinct from e.personal
    where g.id is null) z;
  select string_agg(id, ', ' order by id) into extra from (
    select g.id from geo_fences_for('{uid}','{case['day']}') g
    left join _fx_expect e on e.id = g.id where e.id is null) z;
  select count(*) into n from geo_fences_for('{uid}','{case['day']}');
  if missing is not null then
    raise exception 'geo_fences_for MISSING or WRONG: %. The SQL half disagrees with tests/fixtures/geo-fences-case.json, which the browser half is also checked against.', missing;
  end if;
  if extra is not null then
    raise exception 'geo_fences_for produced fences the fixture does not expect: %', extra;
  end if;
  raise notice 'ok   geo_fences_for: % fences, identical to the fixture the browser half uses', n;
end $chk$;
rollback;
"""
(root / 'scripts/ci/geo-fences-equivalence.sql').write_text(out)
print('regenerated scripts/ci/geo-fences-equivalence.sql')
