-- Device-wide Location Services is a THIRD axis, independent of the other two.
--
-- Owner, 2026-08-25: "device wide location services, look up what was new since
-- old was deprecated ... why do we need it?"
--
-- Because the per-app grant and the global switch move independently. Turning
-- off Settings > Privacy & Security > Location Services leaves this app's own
-- authorizationStatus reporting .authorizedAlways completely untouched, while
-- not a single fix will ever arrive again. Without this column a phone in that
-- state is indistinguishable from a healthy one: location_status says 'always',
-- location_accuracy says 'full', and the pings are simply absent with nothing
-- anywhere saying why. That is the exact shape of a live account we have been
-- chasing.
--
-- Three-valued on purpose:
--   true   Location Services is on device-wide, iOS said so
--   false  the master switch is off, iOS said so
--   null   the shell could not answer (a build older than this one, or the
--          plain web app, which has no such concept at all)
--
-- null must never be read as false. "We do not know" and "the switch is off"
-- are different diagnoses and lead to different messages to the crew member.
--
-- Source: CLLocationManager.locationServicesEnabled(), read off the main thread
-- in TdGeoPlugin.locationPermStatus. Not deprecated, contrary to an earlier
-- note in that file: what Apple added is a main-thread runtime warning, because
-- it is a synchronous cross-process lookup that blocks the caller. iOS 18's
-- CLServiceSession diagnostics expose the same fact as authorizationDeniedGlobally
-- without blocking, but that is iOS 18+ against a 15.0 deployment target, and
-- constructing a session takes an authorization requirement, so a plain status
-- query could raise a permission prompt.
--
-- Additive only (CLAUDE.md 3.1). Existing rows keep null, which is honest: they
-- were written by a shell that could not answer this.
alter table device_status add column if not exists location_services_enabled boolean;
